
name: CI

on:
 workflow_dispatch:

jobs:
 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: checking node js
        run: node --version
      - name: setup node js environment
        uses: actions/setup-node@v3.0.0
      - name: checking npm package manager
        run: npm --version
      - name: installing npm package manager
        run: sudo apt install npm
      - name: checking new verion of npm
        run: npm --version
      - name: installing angular cli
        run: npm i -g @angular/cli
#       - name: installing linting tools
#         run: npm install @angular-devkit/build-angular:tslint
#       - name: npm ci
#         run: npm ci
#       - name: run linting against project
#         run: npm run lint
   
#       - name: Super-Linter
#         uses: github/super-linter@v4.9.1
#         env: 
#           DEFAULT_BRANCH: main
#           VALIDATE_CSS: true
#           VALIDATE_JSON: true
#           VALIDATE_HTML: true
#           VALIDATE_JSCPD: true
#           VALIDATE_TYPESCRIPT_STANDARD: true
#           EDITORCONFIG_FILE_NAME: .ecrc
#           OUTPUT_FORMAT: tap
#           OUTPUT_FOLDER: report
      - name: setup lit
        run: npm install @angular-extensions/lint-rules --save-dev
      - name: running linting
        run: ng lint
          
      - name: checking report
        run: ls ./report
        
        
   
