

name: SonarQube Scanning

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: dotnet --version
      - name: Run a multi-line script
        run: |
          echo dotnet --versioin
#       - name: Install dependencies
#         run: dotnet add package Newtonsoft.Json --version 12.0.1       
        
      - name: checking path
        run: |
             pwd
             ls
             ls ./github
             
             
        
