
name: SonarQube Scanning

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: dotnet --version
      - name: Run a multi-line script
        run: |
          echo dotnet --versioin
      - name: Setup .NET 5.0.405
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: '5.0.405'
      - name: check --version  
        run: dotnet --version      
