
name: SonarQube Scanning

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: uninstall sdks
        run: apt-get remove dotnet-host
      - name: setup dotNet
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: '6.0.200'
      - name: check --version  
        run: dotnet --version  
      - name: check SDKS  
        run: dotnet --list-sdks
      - name: check runtime  
        run: dotnet --list-runtimes
        
#       - name: Restore dependencies
#         run: dotnet restore
#       - name: Install dependencies
#         run: dotnet add package Newtonsoft.Json --version 12.0.1  
#       - name: checking dependencies
#         run: ls
